/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package View;

import Control.DaoPessoa;
import Model.Pessoa;
import java.sql.SQLException;
import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.text.MaskFormatter;

/**
 *
 * @author Felipe de Souza Yamaoka e Brunão
 */
public class GuiPessoa extends javax.swing.JFrame {

    /**
     * Creates new form GuiPessoa
     */
    public GuiPessoa() {
        initComponents();
        formatarCampo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        LabelCodigo = new javax.swing.JLabel();
        TextFieldCodigo = new javax.swing.JTextField();
        LabelTipoPessoa = new javax.swing.JLabel();
        ComboBoxTipoPessoa = new javax.swing.JComboBox<>();
        LabelCodigo1 = new javax.swing.JLabel();
        TextFieldNome = new javax.swing.JTextField();
        LabelApelido = new javax.swing.JLabel();
        TextFieldApelido = new javax.swing.JTextField();
        TextFieldDescricao = new javax.swing.JTextField();
        LabelDescricao = new javax.swing.JLabel();
        TextFieldEndereco = new javax.swing.JTextField();
        LabelEndereco = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        LabelTitutloNovoCadastro = new javax.swing.JLabel();
        LabelBairro = new javax.swing.JLabel();
        TextFieldBairro = new javax.swing.JTextField();
        LabelNumero = new javax.swing.JLabel();
        TextFieldCidade = new javax.swing.JTextField();
        LabelCidade = new javax.swing.JLabel();
        TextFieldNumero = new javax.swing.JTextField();
        LabelUF = new javax.swing.JLabel();
        ComboBoxUF = new javax.swing.JComboBox<>();
        LabelCEP = new javax.swing.JLabel();
        LabelFone = new javax.swing.JLabel();
        LabelNumeroRegistro = new javax.swing.JLabel();
        TextFieldNumeroRegistro = new javax.swing.JTextField();
        ButtonCadastrar = new javax.swing.JButton();
        ButtonCadastrar1 = new javax.swing.JButton();
        FormattedTextFieldCEP = new javax.swing.JFormattedTextField();
        FormattedTextFieldFone = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SISTEMA DE VENDAS");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(51, 51, 51));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 278, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 578, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 280, 580));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        LabelCodigo.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        LabelCodigo.setText("Código");

        TextFieldCodigo.setEditable(false);
        TextFieldCodigo.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        TextFieldCodigo.setToolTipText("");
        TextFieldCodigo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TextFieldCodigoMouseClicked(evt);
            }
        });

        LabelTipoPessoa.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        LabelTipoPessoa.setText("Tipo de Pessoa");

        ComboBoxTipoPessoa.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        ComboBoxTipoPessoa.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Funcionário", "Fornecedor", "Cliente" }));

        LabelCodigo1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        LabelCodigo1.setText("Nome");

        TextFieldNome.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        TextFieldNome.setToolTipText("");

        LabelApelido.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        LabelApelido.setText("Apelido");

        TextFieldApelido.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        TextFieldApelido.setToolTipText("");

        TextFieldDescricao.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        TextFieldDescricao.setToolTipText("");

        LabelDescricao.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        LabelDescricao.setText("Descrição");

        TextFieldEndereco.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        TextFieldEndereco.setToolTipText("");

        LabelEndereco.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        LabelEndereco.setText("Endereço");

        jPanel1.setBackground(new java.awt.Color(0, 204, 255));

        LabelTitutloNovoCadastro.setFont(new java.awt.Font("Arial", 1, 44)); // NOI18N
        LabelTitutloNovoCadastro.setForeground(new java.awt.Color(255, 255, 255));
        LabelTitutloNovoCadastro.setText("Novo Cadastro");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(114, 114, 114)
                .addComponent(LabelTitutloNovoCadastro)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(LabelTitutloNovoCadastro)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        LabelBairro.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        LabelBairro.setText("Bairro");

        TextFieldBairro.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        TextFieldBairro.setToolTipText("");

        LabelNumero.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        LabelNumero.setText("Número");

        TextFieldCidade.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        TextFieldCidade.setToolTipText("");

        LabelCidade.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        LabelCidade.setText("Cidade");

        TextFieldNumero.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        TextFieldNumero.setToolTipText("");

        LabelUF.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        LabelUF.setText("UF");

        ComboBoxUF.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        ComboBoxUF.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "AC", "AL", "AP", "AM", "BA", "CE", "DF", "ES", "GO", "MA", "MT", "MS", "MG", "PA", "PB", "PR", "PE", "PI", "RJ", "RN", "RS", "RO", "RR", "SC", "SP", "SE", "TO" }));

        LabelCEP.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        LabelCEP.setText("CEP");

        LabelFone.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        LabelFone.setText("Fone");

        LabelNumeroRegistro.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        LabelNumeroRegistro.setText("Número de Registro");

        TextFieldNumeroRegistro.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        TextFieldNumeroRegistro.setToolTipText("");

        ButtonCadastrar.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        ButtonCadastrar.setText("CADASTRAR");
        ButtonCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonCadastrarActionPerformed(evt);
            }
        });

        ButtonCadastrar1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        ButtonCadastrar1.setText("SAIR");
        ButtonCadastrar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonCadastrar1ActionPerformed(evt);
            }
        });

        try {
            FormattedTextFieldCEP.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#####-###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        FormattedTextFieldCEP.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        try {
            FormattedTextFieldFone.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)#####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        FormattedTextFieldFone.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(39, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LabelCodigo)
                            .addComponent(LabelCodigo1)
                            .addComponent(LabelApelido)
                            .addComponent(LabelDescricao)
                            .addComponent(LabelCEP)
                            .addComponent(LabelBairro)
                            .addComponent(LabelEndereco)
                            .addComponent(LabelCidade)
                            .addComponent(LabelFone))
                        .addGap(73, 73, 73)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(TextFieldEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(TextFieldCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(TextFieldBairro, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(TextFieldDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TextFieldApelido, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TextFieldNome, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TextFieldCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(FormattedTextFieldFone, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(FormattedTextFieldCEP, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(LabelNumeroRegistro)
                        .addGap(10, 10, 10)
                        .addComponent(TextFieldNumeroRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(ButtonCadastrar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ButtonCadastrar1))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LabelTipoPessoa)
                            .addComponent(LabelUF)
                            .addComponent(LabelNumero))
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(TextFieldNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(ComboBoxTipoPessoa, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(ComboBoxUF, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(23, 23, 23))
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LabelCodigo)
                            .addComponent(TextFieldCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TextFieldNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LabelCodigo1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TextFieldApelido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LabelApelido))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TextFieldDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LabelDescricao))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LabelCEP)
                            .addComponent(FormattedTextFieldCEP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TextFieldBairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LabelBairro))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LabelEndereco)
                            .addComponent(TextFieldEndereco, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LabelCidade)
                            .addComponent(TextFieldCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(13, 13, 13)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LabelFone)
                            .addComponent(FormattedTextFieldFone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TextFieldNumeroRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LabelNumeroRegistro)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LabelTipoPessoa)
                            .addComponent(ComboBoxTipoPessoa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(147, 147, 147)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ComboBoxUF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LabelUF))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LabelNumero)
                            .addComponent(TextFieldNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 65, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ButtonCadastrar)
                    .addComponent(ButtonCadastrar1))
                .addGap(33, 33, 33))
        );

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 0, 740, 580));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    public void formatarCampo() {
        try {
            MaskFormatter pCEPmask = new MaskFormatter("#####-###");
            pCEPmask.install(FormattedTextFieldCEP);
        } catch (ParseException ex) {
            System.out.println("Formatar Campo Erro - "+ex);
        }
    }
    private void ButtonCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonCadastrarActionPerformed
        Pessoa pessoa = new Pessoa();
        
        pessoa.setTIP_IN_COD(ComboBoxTipoPessoa.getSelectedIndex()+1);
        pessoa.setPES_ST_NOME(TextFieldNome.getText());
        pessoa.setPES_ST_APELIDO(TextFieldApelido.getText());
        pessoa.setPES_ST_DESCRICAO(TextFieldDescricao.getText());
        pessoa.setPES_ST_ENDERECO(TextFieldEndereco.getText());
        pessoa.setPES_ST_BAIRRO(TextFieldBairro.getText());
        pessoa.setPES_ST_NUMERO(TextFieldNumero.getText());
        pessoa.setPES_ST_CIDADE(TextFieldCidade.getText());
        pessoa.setPES_ST_UF(ComboBoxUF.getSelectedItem().toString());
        pessoa.setPES_ST_CEP(FormattedTextFieldCEP.getText());
        pessoa.setPES_ST_FONE(FormattedTextFieldFone.getText());
        pessoa.setPES_ST_NUMEROREGISTRO(TextFieldNumeroRegistro.getText());
        
        DaoPessoa daoPessoa = new DaoPessoa();
        
        try {
            daoPessoa.Insert(pessoa);
        } catch (SQLException ex) {
            Logger.getLogger(GuiPessoa.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_ButtonCadastrarActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        DaoPessoa daoPessoa = new DaoPessoa();
        
        try {
            TextFieldCodigo.setText(daoPessoa.MaxID());
        } catch (SQLException ex) {
            Logger.getLogger(GuiPessoa.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_formWindowOpened

    private void TextFieldCodigoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TextFieldCodigoMouseClicked

    }//GEN-LAST:event_TextFieldCodigoMouseClicked

    private void ButtonCadastrar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonCadastrar1ActionPerformed
        this.dispose(); // Fecha a Janela e ainda limpa da memória
    }//GEN-LAST:event_ButtonCadastrar1ActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GuiPessoa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GuiPessoa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GuiPessoa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GuiPessoa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GuiPessoa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonCadastrar;
    private javax.swing.JButton ButtonCadastrar1;
    private javax.swing.JComboBox<String> ComboBoxTipoPessoa;
    private javax.swing.JComboBox<String> ComboBoxUF;
    private javax.swing.JFormattedTextField FormattedTextFieldCEP;
    private javax.swing.JFormattedTextField FormattedTextFieldFone;
    private javax.swing.JLabel LabelApelido;
    private javax.swing.JLabel LabelBairro;
    private javax.swing.JLabel LabelCEP;
    private javax.swing.JLabel LabelCidade;
    private javax.swing.JLabel LabelCodigo;
    private javax.swing.JLabel LabelCodigo1;
    private javax.swing.JLabel LabelDescricao;
    private javax.swing.JLabel LabelEndereco;
    private javax.swing.JLabel LabelFone;
    private javax.swing.JLabel LabelNumero;
    private javax.swing.JLabel LabelNumeroRegistro;
    private javax.swing.JLabel LabelTipoPessoa;
    private javax.swing.JLabel LabelTitutloNovoCadastro;
    private javax.swing.JLabel LabelUF;
    private javax.swing.JTextField TextFieldApelido;
    private javax.swing.JTextField TextFieldBairro;
    private javax.swing.JTextField TextFieldCidade;
    private javax.swing.JTextField TextFieldCodigo;
    private javax.swing.JTextField TextFieldDescricao;
    private javax.swing.JTextField TextFieldEndereco;
    private javax.swing.JTextField TextFieldNome;
    private javax.swing.JTextField TextFieldNumero;
    private javax.swing.JTextField TextFieldNumeroRegistro;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    // End of variables declaration//GEN-END:variables
}
